version: '3.8'

services:
  dev-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Bind mount for hot reload - changes in host are reflected in container
      - ./app.py:/app/app.py:ro
      # Optional: mount entire directory for development
      # - .:/app
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
